plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: _sass/

# Settings
title: "Women Who Code London"
subtitle: "Mentoring Program"
description: "Mentoring Program"
author: Adriana Zenck Zimmermann

# GitHub
github:
  repository_url: https://github.com/dricazenck/dricazenck.github.io
